In [14]:
import numpy as np
a=np.array ([0,1,2,3,4])
a[0]
a[1]
a[4]

a.size    #numero de elementos que hay en la matriz
a.ndim    #dimensiones o rango de la matriz
a.shape   # es una tupla de numero enteros que indica el tamaño

(5,)

In [15]:
from numpy.core.getlimits import array
c=np.array ([20,1,2,3,4])
c:array ([20,1,2,3,4])
c[0]=100
c=array

In [16]:
c:array ([100,1,2,3,0])

c=array

In [17]:
import numpy as np
#u=[1,0]
#v=[0,1]
z=[]
#for n, m in zip(u,v)
#z.append(n+m)
a=np.array([1,-1,1,-1])
mean_a=a.mean()

In [18]:
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [19]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [20]:
a = np.array([10, 2, 30, 40,50])
a[1]=20
a

array([10, 20, 30, 40, 50])

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[1:8:2])

[2 4 6 8]


In [22]:
b = np.array([10, 20, 30, 40, 50, 60, 70])
b.size  #Elementos Matriz
b.ndim #dimensiones
b.shape  # tupla

(7,)

In [23]:
c = np.array([-10, 201, 43, 94, 502])
max_C= c.max()
max_C

502

In [24]:
c = np.array([-10, 201, 43, 94, 502])
min_C= c.min()
min_C

-10

In [25]:
c = np.array([-10, 201, 43, 94, 502])
max_C= c.max()
max_C

min_C= c.min()
min_C
c = np.array([-10, 201, 43, 94, 502])
sum= (max_C + min_C)
sum

492

In [26]:
a = [[11,12,13],[21,22,23],[31,32,33]]
a=np.array(a)
a.ndim
a.shape
a.size

9

In [27]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
a.ndim

2

In [ ]:
#A = np.array([[1,2],[3,4],[5,6],[7,8]])
#B = np.array([[1,2,3],[4,5,6],[7,8,9]])
#np.dot(a,b)

In [28]:
a =np.array([[1,2,3,4], [5,6,7,8] , [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
import numpy as np
A= np.array ([[11,12], [21,22] , [31,32]])
type(A)
A.shape
A.dtype
A[1]

array([21, 22])

In [37]:
A= np.array ([[11,12], [21,22]])
B= np.array ([[1,0], [0,1]])
C= A*B

In [38]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [39]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [40]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [42]:
A= np.array ([[11,12], [21,22]])
B= np.array ([[1,0], [0,1]])
np.dot(A,b)

array([11, 21])

In [43]:
3+2*2

7

In [44]:
int(3.2)

3

In [45]:
A=("1234567")
A[1::2]

'246'

In [46]:
A="1"
B="2"
A+B

'12'

In [50]:
#F = "Está equivocado"
#F.superior(F)

In [51]:
tuple1=("A","B","C" )
tuple1[-1]

'C'

In [52]:
A=((11,12),[21,22])
A[1]

[21, 22]

In [53]:
A=((11,12),[21,22])
A[0][1]

12

In [54]:
'1,2,3,4'.split(',')

['1', '2', '3', '4']

In [56]:
A=[1,'a']
B=[2,1,'d']
A+B

[1, 'a', 2, 1, 'd']

In [58]:
V={'A','B'}
V.add('C')

In [63]:
A=['1','2','3']

print(2 * a)

[2 2 2 2 2]
